import { Config } from "./src/config";

export const defaultConfig: Config = {
  url: "https://virtocommerce.com/sitemap/main_sitemap.xml",
  match: [
    "https://virtocommerce.com/*",
    "https://virtocommerce.com/solutions/*",
    "https://virtocommerce.com/solution/*",
    "https://virtocommerce.com/industry/*",
    "https://virtocommerce.com/case-studies/*",
    "https://virtocommerce.com/commerce-engine/*",
    "https://virtocommerce.com/marketplace/*",
    "https://virtocommerce.com/portal/*",
    "https://virtocommerce.com/capabilities/*",
    "https://virtocommerce.com/integrations/*",
    "https://virtocommerce.com/features/*",
    "https://virtocommerce.com/assets/*",
    "https://virtocommerce.com/assets/category/*",
    "https://virtocommerce.com/resources/*",
    "https://virtocommerce.com/products/*",
  ],
  exclude: [
    "https://virtocommerce.com/blog",
    "https://virtocommerce.com/blog/*",
    "https://virtocommerce.com/become-a-partner",
    "https://virtocommerce.com/privacy",
    "https://virtocommerce.com/terms",
    "https://virtocommerce.com/cookies",
    "https://virtocommerce.com/download*",
    "https://virtocommerce.com/*thank-you*",
    "https://virtocommerce.com/assets-download/*",
    "https://virtocommerce.com/asset-download-thank-*",
    "https://virtocommerce.com/newsletter-subscription",
    "https://virtocommerce.com/docs",
    "https://virtocommerce.com/docs/*",
  ],
  maxPagesToCrawl: 1000,
  waitForSelectorTimeout: 5000,
  outputFileName: "output.json",
  selector: "main",
};
